#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EmployeeDatabase")]
	public partial class EmployeeDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    #endregion
		
		public EmployeeDataClassesDataContext() : 
				base(global::WpfApp1.Properties.Settings.Default.EmployeeDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmployeeDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Emp_ID;
		
		private string _Emp_FName;
		
		private string _Emp_LName;
		
		private System.Nullable<int> _Emp_Age;
		
		private System.Nullable<System.DateTime> _Emp_DBO;
		
		private string _Emp_Email;
		
		private string _Emp_Gender;
		
		private string _Emp_Dept;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmp_IDChanging(int value);
    partial void OnEmp_IDChanged();
    partial void OnEmp_FNameChanging(string value);
    partial void OnEmp_FNameChanged();
    partial void OnEmp_LNameChanging(string value);
    partial void OnEmp_LNameChanged();
    partial void OnEmp_AgeChanging(System.Nullable<int> value);
    partial void OnEmp_AgeChanged();
    partial void OnEmp_DBOChanging(System.Nullable<System.DateTime> value);
    partial void OnEmp_DBOChanged();
    partial void OnEmp_EmailChanging(string value);
    partial void OnEmp_EmailChanged();
    partial void OnEmp_GenderChanging(string value);
    partial void OnEmp_GenderChanged();
    partial void OnEmp_DeptChanging(string value);
    partial void OnEmp_DeptChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Emp_ID
		{
			get
			{
				return this._Emp_ID;
			}
			set
			{
				if ((this._Emp_ID != value))
				{
					this.OnEmp_IDChanging(value);
					this.SendPropertyChanging();
					this._Emp_ID = value;
					this.SendPropertyChanged("Emp_ID");
					this.OnEmp_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_FName", DbType="VarChar(50)")]
		public string Emp_FName
		{
			get
			{
				return this._Emp_FName;
			}
			set
			{
				if ((this._Emp_FName != value))
				{
					this.OnEmp_FNameChanging(value);
					this.SendPropertyChanging();
					this._Emp_FName = value;
					this.SendPropertyChanged("Emp_FName");
					this.OnEmp_FNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_LName", DbType="NVarChar(50)")]
		public string Emp_LName
		{
			get
			{
				return this._Emp_LName;
			}
			set
			{
				if ((this._Emp_LName != value))
				{
					this.OnEmp_LNameChanging(value);
					this.SendPropertyChanging();
					this._Emp_LName = value;
					this.SendPropertyChanged("Emp_LName");
					this.OnEmp_LNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Age", DbType="Int")]
		public System.Nullable<int> Emp_Age
		{
			get
			{
				return this._Emp_Age;
			}
			set
			{
				if ((this._Emp_Age != value))
				{
					this.OnEmp_AgeChanging(value);
					this.SendPropertyChanging();
					this._Emp_Age = value;
					this.SendPropertyChanged("Emp_Age");
					this.OnEmp_AgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_DBO", DbType="Date")]
		public System.Nullable<System.DateTime> Emp_DBO
		{
			get
			{
				return this._Emp_DBO;
			}
			set
			{
				if ((this._Emp_DBO != value))
				{
					this.OnEmp_DBOChanging(value);
					this.SendPropertyChanging();
					this._Emp_DBO = value;
					this.SendPropertyChanged("Emp_DBO");
					this.OnEmp_DBOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Email", DbType="VarChar(50)")]
		public string Emp_Email
		{
			get
			{
				return this._Emp_Email;
			}
			set
			{
				if ((this._Emp_Email != value))
				{
					this.OnEmp_EmailChanging(value);
					this.SendPropertyChanging();
					this._Emp_Email = value;
					this.SendPropertyChanged("Emp_Email");
					this.OnEmp_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Gender", DbType="VarChar(50)")]
		public string Emp_Gender
		{
			get
			{
				return this._Emp_Gender;
			}
			set
			{
				if ((this._Emp_Gender != value))
				{
					this.OnEmp_GenderChanging(value);
					this.SendPropertyChanging();
					this._Emp_Gender = value;
					this.SendPropertyChanged("Emp_Gender");
					this.OnEmp_GenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Dept", DbType="VarChar(50)")]
		public string Emp_Dept
		{
			get
			{
				return this._Emp_Dept;
			}
			set
			{
				if ((this._Emp_Dept != value))
				{
					this.OnEmp_DeptChanging(value);
					this.SendPropertyChanging();
					this._Emp_Dept = value;
					this.SendPropertyChanged("Emp_Dept");
					this.OnEmp_DeptChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
